# Generated by Django 3.1 on 2020-08-22 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0003_auto_20200818_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareaproyecto',
            old_name='horas',
            new_name='horas_facturables',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='supervisor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('Tarea Campo', 'Tarea Campo'), ('Gabinete', 'Gabinete')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='codigo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='tipo HH'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_de_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_de_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tareaproyecto',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='tareaproyecto',
            name='horas_no_facturables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
