# Generated by Django 3.1 on 2020-08-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20200822_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='tipo HH'),
        ),
    ]
