# Generated by Django 3.1 on 2020-08-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_proyecto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Nº de servicio'),
        ),
    ]
